//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tEmployeeEntities : DbContext
    {
        public tEmployeeEntities()
            : base("name=tEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAdmin> tAdmin { get; set; }
        public virtual DbSet<tCategory> tCategory { get; set; }
        public virtual DbSet<tOrder> tOrder { get; set; }
        public virtual DbSet<tOrderDetails> tOrderDetails { get; set; }
        public virtual DbSet<tProduct> tProduct { get; set; }
        public virtual DbSet<tShoppingCar> tShoppingCar { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
    }
}
